### ISSUE TITLE
implement missing methods from delta/rich-text

### ISSUE THREAD

**Issue by dwelle** [ottypes/text-unicode#2]
Is there a reason why `ottypes/text-unicode` et al. is missing certain utility methods  implemented in `quill/delta`? The `diff` method would be particularly useful. Would you be open for a PR to include at least that, or the idea is to keep as smallest API as possible?

**Comment by josephg** [comment]
I'd like to keep this small, but that is generally useful... I could go either way on that question. Would it be a big method?

**Comment by dwelle** [comment]
It seems not quite :blush: --- my plan was to mostly copy-paste from [quill/delta#L267-L322](https://github.com/quilljs/delta/blob/master/src/Delta.ts#L267-L322) which also uses [fast-diff](https://github.com/jhchen/fast-diff/blob/master/diff.js). Would have to try to figure out minified SLOC, tho.

**Comment by josephg** [comment]
Yeah I'm not going to copy+paste that method into this library. Please include it separately if you're after that functionality! (Or put it in an npm module)
