### ISSUE TITLE
Invert support

### ISSUE THREAD

**Issue by josephg** [ottypes/text-unicode#3]
Tracker issue for invert support. This is needed for the [equivalent feature](https://github.com/ottypes/json1/issues/11) in [json1](https://github.com/ottypes/json1/issues/11).

There's two pieces of functionality I'm adding here:

1. Allow users to create inverted operations when a document is known. So, given a document `doc` and an operation `op` on that document, generate `op'` such that `apply(apply(doc, op), op') === doc` and `compose(op, op') === noop`.
2. Allow operations themselves to optionally embed information about deleted characters.

(1) is easy, and as of today its working - though I'm still not 100% sure what to call the method.

(2) has a few tricky bits:

- OT is complicated enough without users also needing to keep track of invertible and non-invertible operation variants
- The API here is going to be really error prone - eg, if you make an operation invertible, will it stay invertible once you transform or compose it with another operation? This is doable for text-unicode, but impossible in json1.

My plan at the moment is to add support for both pieces of functionality, but recommend people just use the simple helper for inverting an operation in the context of a document.

**Comment by Jocs** [comment]
Hi, I found that the `invert` function has been added to the code. When will the new version be released? thanks.

**Comment by josephg** [comment]
Out of curiosity, what context are you using the text type in? Sharedb or something else?

**Comment by Jocs** [comment]
I use `ot-json1` in [muya](https://github.com/marktext/muya), muya is a markdown editor, currently under development, the underlying data uses json1, because it needs to support `undo` and  `redo`, so I hope the operation of json1 supports invertable, so `text-unicode` also need to support invertable. With the help of json1, muya may also support multi-person collaboration in the future.

**Comment by josephg** [comment]
Cool! I’ll get a release of text-unicode out tomorrow. There’s some foot guns I want to write about in the readme with invert, since you can have both invertable and non invertable operations. 

Undo with json1 will take a bit more time because it’s not my priority right now.

**Comment by josephg** [comment]
📦 ot-text-unicode@4.0.0
